
############### BACKEND_WEBPPJ
GET http://localhost:7000


################################################################# [USERS]
### -> USERS API -> GET USERS
GET http://localhost:7000/api/users
### -> USERS API -> GET USER/:id
GET http://localhost:7000/api/users/20231211133753643
### -> USERS API -> GET USER/:nickname
GET http://localhost:7000/api/users/user/@7V
### -> USERS API -> GET USER/VIEWER
POST http://localhost:7000/api/users/viewer?list=20231211133753643,20231211163214134
### -> USERS API -> POST CREATE USER
POST http://localhost:7000/api/users/new
content-type: application/json

{
    "last_name": "Nguyễn Vũ"
}

### -> USERS API -> PUT UPDATE USER
PUT http://localhost:7000/api/users/update/20231211133753643
content-type: application/json

{
}



################################################################# [ACCOUNTS]
### -> ACCOUNTS API -> GET ACCOUNTS
GET http://localhost:7000/api/accounts
### -> ACCOUNTS API -> POST CREATE ACCOUNT -> ADMIN
POST http://localhost:7000/api/accounts/create
content-type: application/json

{
    "user_id": "20231211133753643",
    "username": "7v52admin",
    "password": "admin777",
    "role": 7
}

### -> ACCOUNTS API -> POST CREATE ACCOUNT -> USER
POST http://localhost:7000/api/accounts/create
content-type: application/json

{
    "user_id": "0000",
    "username": "user1",
    "password": "user1"
}

### -> ACCOUNTS API -> POST ACCOUNT SIGN-IN -> NORMAL
POST http://localhost:7000/api/accounts/signin
content-type: application/json

{
    "username": "7v52admin",
    "password": "admin777"
}



################################################################# [BLOGS]
### -> BLOGS API -> GET BLOGS
GET http://localhost:7000/api/blogs
### -> BLOGS API -> GET BLOGS/:id
GET http://localhost:7000/api/blogs/20231218094958180
### -> BLOGS API -> GET BLOGS/USER/:PAGE
GET http://localhost:7000/api/blogs/user/@user20231211163214451
### -> BLOGS API -> POST CREATE BLOG
POST http://localhost:7000/api/blogs/new
content-type: application/json

{
    "owner": { 
        "name": "Nguyễn Vũ",
        "avatar": [
            {
                "filename": "admin.png",
                "url": "http://localhost:7000/images/avatars/admin.png"
            }
        ],
        "page_url": "@7V"
    },
    "content": {
        "thumbnail": [
            {
                "filename": "thumbnail.jpg",
                "url": "http://localhost:7000/images/blogs/thumbnail.jpg"
            }
        ],
        "title": "SAD THỦ FOREVER 1",
        "content": "Một dĩa mồi khô, một kết bia\nMột chai rượu nếp, một cái thìa\nChẳng được nên đôi, cô đơn mãi\nMột mình ngồi nhậu, quẩy zìa zia!!\n\n-- Nguyen Vu --"
    },
    "view": 979578
}

### -> BLOGS API -> PUT UPDATE USER
PUT http://localhost:7000/api/blogs/update/20231211133753643
content-type: application/json
{
}



################################################################# [PAGES]
### -> PAGES API -> GET PAGES
GET http://localhost:7000/api/pages
### -> PAGES API -> GET USER/:id
GET http://localhost:7000/api/pages/213
### -> PAGES API -> POST CREATE BLOG
POST http://localhost:7000/api/pages/new
content-type: application/json

{
    "owner_id": "20231211133753643",
    "content": {
        "thumbnail": {
            "filename": "thumbnail.jpg",
            "url": "http://localhost:7000/images/blogs/thumbnail.jpg"
        },
        "title": "SAD THỦ FOREVER 7",
        "content": "<p>Một dĩa mồi khô, một kết bia<br />Một chai rượu nếp, một cái thìa<br />Chẳng được một đôi như đôi đũa<br />Một mình ngồi nhậu, quẩy zìa zia!!</p><p>&nbsp;</p><p>-- Nguyen Vu --</p>"
    },
    "view": 7
}

### -> PAGES API -> PUT UPDATE USER
PUT http://localhost:7000/api/blogs/update/20231211133753643
content-type: application/json
{
}



################################################################# [EVENTS]
### -> EVENTS API -> GET EVENTS
GET http://localhost:7000/api/events
### -> EVENTS API -> GET USER/:id
GET http://localhost:7000/api/events/213
### -> EVENTS API -> POST CREATE BLOG
POST http://localhost:7000/api/events/new
content-type: application/json

{
    "owner_id": "20231211133753643",
    "content": {
        "thumbnail": {
            "filename": "thumbnail.jpg",
            "url": "http://localhost:7000/images/blogs/thumbnail.jpg"
        },
        "title": "SAD THỦ EVENT 7",
        "content": "<p>Một dĩa mồi khô, một kết bia<br />Một chai rượu nếp, một cái thìa<br />Chẳng được một đôi như đôi đũa<br />Một mình ngồi nhậu, quẩy zìa zia!!</p><p>&nbsp;</p><p>-- Nguyen Vu --</p>"
    },
    "view": 7
}

### -> EVENTS API -> PUT UPDATE USER
PUT http://localhost:7000/api/blogs/update/20231211133753643
content-type: application/json
{
}

###
{
    "info": {
        "first_name": "Nguyễn",
        "last_name": "Vũ",
        "full_name": "Nguyễn Vũ",
        "nick_name": "7V",
        "bio": "Không muốn làm MC - Chỉ muốn làm Em Vui",
        "description": "Admin & Manager of PJ",
        "birth": "04/05/2002",
        "contact": {
            "phone": "0358802875",
            "email": "nguyenvu2319@gmail.com",
            "socials": [
                {
                    "name": "Facebook",
                    "hyperlink": "Nguyễn Vũ",
                    "url": "https://www.facebook.com/nguyenvu.version2319.vn"
                },
                {
                    "name": "TikTok",
                    "hyperlink": "@_7v_52",
                    "url": "https://www.tiktok.com/@_7v_52"
                },
                {
                    "name": "Youtube",
                    "hyperlink": "7V Nguyễn Vũ",
                    "url": "https://www.youtube.com/@7vnguyenvu52"
                },
                {
                    "name": "Github",
                    "hyperlink": "Nguyễn Vũ",
                    "url": "https://github.com/vunguyen-dev-er"
                }
            ]
        }
    },
    "images": {
        "avatar": [
            {
                "filename": "admin.png",
                "url": "http://localhost:7000/images/avatars/admin.png"
            }
        ],
        "cover": [
            {
                "filename": "admin.jpg",
                "url": "http://localhost:7000/images/cover-images/admin.jpg"
            }
        ]
    }
    
}
###



### -> REST API -> POST USER SIGN-IN -> WITH TOKEN
POST http://localhost:7000/users/signin
content-type: application/json
x-auth-token: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NGVkOTQzMmU3NTc5ZjRmYjJlMzQ2YmMiLCJjb2RlIjoiMWFkNzM0M2NmNThhNGIyNGJhNTQ2YzcwMDE5NzA0MTQiLCJhY2NvdW50IjoidXNlcjEiLCJyb2xlIjowLCJmaXJzdF9uYW1lIjoiXyIsImxhc3RfbmFtZSI6Ik5nxrDhu51pIGTDuW5nIDEiLCJuaWNrX25hbWUiOiJ1c2VyMjE5NDQ0NjY4MzM2MjMzMjExMzYiLCJiaXJ0aCI6Il8iLCJkZXNjcmlwdGlvbiI6Il8iLCJiaW8iOiJfIiwiYXZhdGFyIjoiXyIsImNvdmVyX2ltYWdlIjoiXyIsImNvbnRhY3QiOnsicGhvbmUiOiJfIiwiZW1haWwiOiJfIiwic29jaWFscyI6eyJmYWNlYm9vayI6Il8iLCJpbnN0YWdyYW0iOiJfIiwidGlrdG9rIjoiXyIsInlvdXR1YmUiOiJfIiwiZ2l0aHViIjoiXyJ9fSwiZnJpZW5kcyI6W10sImNyZWF0ZWRBdCI6IjIwMjMtMDgtMjlUMDY6NDY6MTAuMTAzWiIsInVwZGF0ZWRBdCI6IjIwMjMtMDgtMjlUMDY6NDY6MTAuMTAzWiIsIl9fdiI6MCwiaWF0IjoxNjkzMjkyNDMxfQ.HIKTUWraHDtpB-cQvfcnVZbFe9T4B36pNkEHSFxiKVQ



